const menu = [
  {
    id: 1,
    title: '雞腿飯',
    category: '熱門推薦',
    price: 110,
    img: '/images/念之為小圖/DSC06164.JPG',
    desc: `現炸雞腿，多汁鮮嫩，飽足感十足。 `,
  },
  {
    id: 2,
    title: '排骨飯',
    category: '熱門推薦',
    price: 95,
    img: '/images/念之為小圖/DSC06168.JPG',
    desc: `淡淡的胡椒香，令人忍不住一口接一口，是本店必點的招牌。 `,
  },
  {
    id: 3,
    title: '鯖魚飯',
    category: '熱門推薦',
    price: 100,
    img: '/images/念之為小圖/DSC06165.JPG',
    desc: `肉質緊實，油脂豐富，是低脂肪高蛋白的好食材。`,
  },
  {
    id: 4,
    title: '懷舊便當',
    category: '熱門推薦',
    price: 110,
    img: '/images/念之為小圖/DSC06169.JPG',
    desc: `白飯上鋪滿了配菜，圓形的餐盒形狀，主餐為滷排骨，充滿了復古懷念的情感。`,
  },
  {
    id: 5,
    title: '蝦捲飯',
    category: '熱門推薦',
    price: 90,
    img: '/images/念之為小圖/DSC06166.JPG',
    desc: `蝦捲新鮮，蝦肉飽滿，口感彈牙，讓每一口都能吃到蝦捲的美味。 `,
  },
  {
    id: 6,
    title: '綜合飯',
    category: '搭配完美',
    price: 95,
    img: '/images/念之為小圖/DSC06179.JPG',
    desc: `爌肉，蝦捲，蒜泥白肉，專為喜歡嚐鮮，挑惕的嘴設計。`,
  },
  {
    id: 7,
    title: '照燒豬排飯',
    category: '搭配完美',
    price: 95,
    img: '/images/念之為小圖/DSC06172.JPG',
    desc: `豬排的厚度適中，表面焦香，內里軟嫩。照燒醬的味道濃郁，甜鹹適中，與豬排的味道相得益彰。 `,
  },
  {
    id: 8,
    title: '雞排飯',
    category: '搭配完美',
    price: 95,
    img: '/images/念之為小圖/DSC06171.JPG',
    desc: `雞排外酥內嫩，飯粒分明，一口下去，滿嘴都是美味的滋味。 `,
  },
  {
    id: 9,
    title: '爌肉飯',
    category: '非炸類',
    price: 95,
    img: '/images/念之為小圖/DSC06180.JPG',
    desc: `肥瘦參半的爌肉飯，是許多人的最愛，每口都是滿足感。`,
  },
  {
    id: 10,
    title: '鱈魚飯',
    category: '搭配完美',
    price: 110,
    img: '/images/念之為小圖/DSC06174.JPG',
    desc: `大塊肥美的鱈魚排，外酥內嫩。`,
  },
  {
    id: 11,
    title: '蒜泥白肉飯',
    category: '非炸類',
    price: 85,
    img: '/images/念之為小圖/DSC06181.JPG',
    desc: `白肉的鮮嫩和蒜泥的香濃在口中交融，飯粒分明，受不了的誘惑。`,
  },
  {
    id: 12,
    title: '卡啦雞腿排飯',
    category: '搭配完美',
    price: 85,
    img: '/images/念之為小圖/DSC06167.JPG',
    desc: `酥炸卡啦雞腿排，雞腿鮮嫩多汁，美味到不行。`,
  },
  {
    id: 13,
    title: '花枝排飯',
    category: '搭配完美',
    price: 85,
    img: '/images/念之為小圖/DSC06173.JPG',
    desc: `口感豐富多層次，新鮮的花枝彷彿置身於大海中。`,
  },
  {
    id: 14,
    title: '排骨特餐',
    category: '大份量',
    price: 165,
    img: '/images/念之為小圖/DSC06178.JPG',
    desc: `主餐為排骨，另有鯖魚，蒜泥白肉，蝦捲，花枝排，半顆滷蛋，肉食主義不能錯過。`,
  },
  {
    id: 15,
    title: '雞腿特餐',
    category: '大份量',
    price: 175,
    img: '/images/念之為小圖/DSC06176.JPG',
    desc: `主餐為雞腿，另有鯖魚，蒜泥白肉，蝦捲，花枝排，半顆滷蛋，給你滿滿的盒餐。`,
  },
  {
    id: 16,
    title: '鱈魚特餐',
    category: '大份量',
    price: 175,
    img: '/images/念之為小圖/DSC06177.JPG',
    desc: `主餐為鱈魚，另有鯖魚，蒜泥白肉，蝦捲，花枝排，半顆滷蛋，吃飽才有體力。`,
  },
  {
    id: 17,
    title: '滷排骨飯',
    category: '搭配完美',
    price: 95,
    img: '/images/念之為小圖/DSC06170.JPG',
    desc: `排骨先炸後滷，香氣四溢，更加軟嫩。`,
  },
  {
    id: 18,
    title: '蔬菜餐盒',
    category: '非炸類',
    price: 65,
    img: '/images/念之為小圖/DSC06175.JPG',
    desc: `沒有主菜，專為特別的您準備的餐盒，不吃肉也是要吃飽才行。`,
  },
]
export default menu
